### ISSUE TITLE
VSCode Error while migrating to Androidx

### ISSUE THREAD

**Issue by maher-saleh** [forrcaho/vscode-flutter-convert-to-androidx#1]
Hello, appreciate helping me in that error message I get when I try to migrate flutter to Androidx using VSCode.

Err message: "Conversion to AndroidX failed: Error: Did not find expected line"

Thanks in advance

**Comment by forrcaho** [comment]
This extension expects to find files exactly as described in the article https://gabrc.medium.com/how-to-migrate-your-flutter-app-to-androidx-1202ad43c8c8 . If the files it finds in your project are not as described in that article, it will produce the error you described.

Is the project you're trying to convert open source? If you can tell me where it is online  (on GitHub or similar), I can take a look.

If it's not something you can share, I'd advise you to try to follow the steps in the article manually, and see if you can find where it differs from the description there. If it's not exactly as described there, but you can still get it to work, please let me know what the difference is and I will fix the extension to cover that case.

**Comment by maher-saleh** [comment]
> This extension expects to find files exactly as described in the article https://gabrc.medium.com/how-to-migrate-your-flutter-app-to-androidx-1202ad43c8c8 . If the files it finds in your project are not as described in that article, it will produce the error you described.
> 
> Is the project you're trying to convert open source? If you can tell me where it is online (on GitHub or similar), I can take a look.
> 
> If it's not something you can share, I'd advise you to try to follow the steps in the article manually, and see if you can find where it differs from the description there. If it's not exactly as described there, but you can still get it to work, please let me know what the difference is and I will fix the extension to cover that case.

Thanks for your prompt reply :) sorry but my project isn't online yet and still saved locally on my PC, I will try following the steps you provided and will let you know the result

**Comment by maher-saleh** [comment]
Sorry but it didn't work .. I followed the instructions from the link you provided but still I get the same error message 
![image](https://user-images.githubusercontent.com/43919279/99196656-75ced900-2796-11eb-86d7-e7350f4a9573.png)

I attached my build.gradle files and properties files

appreciate your help, thanks in advance
[gradle-wrapper.properties.txt](https://github.com/forrcaho/vscode-flutter-convert-to-androidx/files/5543114/gradle-wrapper.properties.txt)
[app-build.gradle.txt](https://github.com/forrcaho/vscode-flutter-convert-to-androidx/files/5543115/app-build.gradle.txt)
[android-build.gradle.txt](https://github.com/forrcaho/vscode-flutter-convert-to-androidx/files/5543116/android-build.gradle.txt)
[gradle.properties.txt](https://github.com/forrcaho/vscode-flutter-convert-to-androidx/files/5543117/gradle.properties.txt)

**Comment by forrcaho** [comment]
None of the projects I've successfully converted with this extension used Kotlin; I think that's why your files are different.

I noticed that all the lines which matched the instructions seem like they've already been changed; e.g compileSdkVersion is already at 28. Are you sure this isn't already converted to AndroidX ?

I'm afraid I don't know the what upgraded Kotlin-using files are supposed to look like, so I can't be of any more help. The other conversion technique is to use Android Studio as described [here](https://developer.android.com/jetpack/androidx/migrate); maybe you can get that to work.

**Comment by maher-saleh** [comment]
Thanks, I think yes I have to refer to android studio problems as you mentioned and may be it is the library itself has a problem and that's why it requests androidx while I'm already using androidx, don't know..
thanks alot :)

**Comment by forrcaho** [comment]
Sorry my extension couldn't help you. If you do find out what changes are needed in cases like yours, you can reopen this issue with that information and I'll try to incorporate it into my code.
